# Generated by Django 2.1.1 on 2018-11-11 02:18

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('things', models.CharField(max_length=50)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '好玩',
                'db_table': 'Interest',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': '分类',
                'db_table': 'type',
            },
        ),
        migrations.AddField(
            model_name='interesting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interesting.Type'),
        ),
    ]
