# Generated by Django 2.1.1 on 2018-10-24 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_of_goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Describe', models.TextField(blank=True)),
                ('Picture', models.ImageField(blank=True, upload_to='category')),
            ],
            options={
                'verbose_name_plural': '产品分类',
                'db_table': 'Category_of_goods',
            },
        ),
        migrations.CreateModel(
            name='Product_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True)),
                ('Describe', models.TextField(blank=True)),
                ('Picture', models.ImageField(blank=True, upload_to='category')),
                ('vlaue', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Already_to_shelves', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('change_time', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category_of_goods')),
            ],
            options={
                'verbose_name_plural': '产品列表',
                'db_table': 'Product_List',
                'ordering': ('-create_time',),
            },
        ),
    ]
