# Generated by Django 2.1.1 on 2018-10-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_list_picture1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_list',
            options={'ordering': ['-create_time'], 'verbose_name_plural': '产品列表'},
        ),
    ]
