# Generated by Django 2.1.1 on 2018-11-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_readnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnum',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
